name: Publish Docker image (amd64)

on:
  push:
    tags:
      - '*'
      - '!*-alpha*'
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false
jobs:
  push_to_registries:
    name: Push Docker image to registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Save version info
        run: |
          git rev-parse --short HEAD > VERSION

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: sjc.vultrcr.com
          ecr: false
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            sjc.vultrcr.com/ehcotest/new-api

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}